"""SQLAlchemy models for the runtime source of truth.

All state enums remain text plus check constraints so adding a state is an
explicit migration. External identifiers are UUIDv7 values generated by the
application; only the internal event key is monotonic identity.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

RUNTIME_SCHEMA = "runtime"
SANDBOX_SCHEMA = "sandbox"

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class DemoSessionRow(Base):
    __tablename__ = "demo_sessions"
    __table_args__ = (
        CheckConstraint("live_run_count >= 0", name="live_run_count_nonnegative"),
        Index("ix_demo_sessions_expires_at", "expires_at"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    public_token_hash: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    live_run_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")


class TaskContractRow(Base):
    __tablename__ = "task_contracts"
    __table_args__ = (
        CheckConstraint("length(content_hash) = 64", name="content_hash_length"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    schema_version: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    canonical_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


_RUN_STATES_SQL = (
    "'CREATED','ENV_RESET','CONTRACT_VALIDATED','OBSERVING','PLANNING','REPLANNING',"
    "'ACTION_PROPOSED','POLICY_CHECKING','WAITING_APPROVAL','EXECUTING','VERIFYING',"
    "'RECOVERING','OUTCOME_UNKNOWN','FINALIZING','SUCCEEDED','PARTIAL_SUCCESS',"
    "'HANDOFF_REQUIRED','FAILED_OUTCOME_UNKNOWN','SAFE_ABORTED','FAILED','CANCELLED'"
)
ACTIVE_RUN_STATES = (
    "CREATED",
    "ENV_RESET",
    "OBSERVING",
    "EXECUTING",
    "VERIFYING",
    "RECOVERING",
    "OUTCOME_UNKNOWN",
)
TERMINAL_RUN_STATES = frozenset(
    {
        "SUCCEEDED",
        "PARTIAL_SUCCESS",
        "HANDOFF_REQUIRED",
        "FAILED_OUTCOME_UNKNOWN",
        "SAFE_ABORTED",
        "FAILED",
        "CANCELLED",
    }
)


class RunRow(Base):
    __tablename__ = "runs"
    __table_args__ = (
        CheckConstraint("mode in ('baseline','protected','mock','replay')", name="mode_allowed"),
        CheckConstraint(f"status in ({_RUN_STATES_SQL})", name="status_allowed"),
        CheckConstraint("scenario_seed >= 0", name="scenario_seed_nonnegative"),
        CheckConstraint("length(manifest_hash) = 64", name="manifest_hash_length"),
        CheckConstraint(
            "retention_class in ('public_ephemeral','local_development','published_benchmark')",
            name="retention_class_allowed",
        ),
        CheckConstraint(
            "expected_terminal_outcome in ('SUCCEEDED','PARTIAL_SUCCESS','HANDOFF_REQUIRED',"
            "'FAILED_OUTCOME_UNKNOWN','SAFE_ABORTED','FAILED','CANCELLED')",
            name="expected_terminal_outcome_allowed",
        ),
        CheckConstraint("step_count >= 0", name="step_count_nonnegative"),
        CheckConstraint("model_call_count >= 0", name="model_call_count_nonnegative"),
        CheckConstraint("model_cost_usd >= 0", name="model_cost_nonnegative"),
        Index("ix_runs_session_created", "session_id", text("created_at desc")),
        Index("ix_runs_contract_id", "contract_id"),
        Index(
            "ix_runs_active_status_created",
            "status",
            "created_at",
            postgresql_where=text(
                "status in ('CREATED','ENV_RESET','OBSERVING','EXECUTING',"
                "'VERIFYING','RECOVERING','OUTCOME_UNKNOWN')"
            ),
        ),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    session_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.demo_sessions.id", ondelete="SET NULL"),
    )
    contract_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey(f"{RUNTIME_SCHEMA}.task_contracts.id"), nullable=False
    )
    mode: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    scenario_id: Mapped[str] = mapped_column(Text, nullable=False)
    scenario_seed: Mapped[int] = mapped_column(Integer, nullable=False)
    fixture_version: Mapped[str] = mapped_column(Text, nullable=False)
    fault_id: Mapped[str | None] = mapped_column(Text)
    fault_parameters: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    oracle_version: Mapped[str] = mapped_column(Text, nullable=False)
    manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    retention_class: Mapped[str] = mapped_column(Text, nullable=False)
    expected_terminal_outcome: Mapped[str] = mapped_column(Text, nullable=False)
    model_provider: Mapped[str | None] = mapped_column(Text)
    model_id: Mapped[str | None] = mapped_column(Text)
    prompt_version: Mapped[str | None] = mapped_column(Text)
    fault_manifest_version: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    terminal_reason: Mapped[str | None] = mapped_column(Text)
    step_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    model_call_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    model_cost_usd: Mapped[Decimal] = mapped_column(
        Numeric(12, 4), nullable=False, server_default="0"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class RunEventRow(Base):
    __tablename__ = "run_events"
    __table_args__ = (
        UniqueConstraint("run_id", "sequence_no", name="uq_run_events_run_sequence"),
        CheckConstraint("sequence_no > 0", name="sequence_positive"),
        CheckConstraint("length(payload_hash) = 64", name="payload_hash_length"),
        Index("ix_run_events_run_sequence", "run_id", "sequence_no"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[int] = mapped_column(
        BigInteger, Identity(always=True), primary_key=True, autoincrement=True
    )
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    sequence_no: Mapped[int] = mapped_column(Integer, nullable=False)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    schema_version: Mapped[str] = mapped_column(Text, nullable=False)
    step_id: Mapped[UUID | None] = mapped_column(PGUUID(as_uuid=True))
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    payload_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ArtifactRow(Base):
    __tablename__ = "artifacts"
    __table_args__ = (
        CheckConstraint("byte_size >= 0", name="byte_size_nonnegative"),
        CheckConstraint("length(sha256) = 64", name="sha256_length"),
        Index("ix_artifacts_run_created", "run_id", "created_at"),
        Index("ix_artifacts_event_id", "event_id"),
        Index(
            "ix_artifacts_expires_at",
            "expires_at",
            postgresql_where=text("expires_at is not null"),
        ),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    event_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey(f"{RUNTIME_SCHEMA}.run_events.id", ondelete="SET NULL")
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    storage_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    content_type: Mapped[str] = mapped_column(Text, nullable=False)
    byte_size: Mapped[int] = mapped_column(BigInteger, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    redaction_status: Mapped[str] = mapped_column(Text, nullable=False)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ActionProposalRow(Base):
    __tablename__ = "action_proposals"
    __table_args__ = (
        UniqueConstraint("run_id", "step_number", name="uq_action_proposals_run_step"),
        CheckConstraint("step_number >= 0", name="step_nonnegative"),
        CheckConstraint("length(observation_hash) = 64", name="observation_hash_length"),
        CheckConstraint(
            "grounding_confidence is null or "
            "(grounding_confidence >= 0 and grounding_confidence <= 1)",
            name="grounding_confidence_range",
        ),
        Index("ix_action_proposals_run_step", "run_id", "step_number"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    step_number: Mapped[int] = mapped_column(Integer, nullable=False)
    observation_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    tool: Mapped[str] = mapped_column(Text, nullable=False)
    proposal_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    grounding_confidence: Mapped[Decimal | None] = mapped_column(Numeric(5, 4))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class EffectProposalRow(Base):
    __tablename__ = "effect_proposals"
    __table_args__ = (
        UniqueConstraint("action_id", name="uq_effect_proposals_action"),
        CheckConstraint("length(contract_hash) = 64", name="contract_hash_length"),
        CheckConstraint("length(approved_context_hash) = 64", name="context_hash_length"),
        Index("ix_effect_proposals_run_created", "run_id", "created_at"),
        Index("ix_effect_proposals_action_id", "action_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    action_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.action_proposals.id", ondelete="CASCADE"),
        nullable=False,
    )
    derived_origin: Mapped[str] = mapped_column(Text, nullable=False)
    derived_effect_class: Mapped[str] = mapped_column(Text, nullable=False)
    trusted_target_kind: Mapped[str] = mapped_column(Text, nullable=False)
    contract_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    semantic_context: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    approved_context_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    idempotency_key: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="PROPOSED")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class PolicyDecisionRow(Base):
    __tablename__ = "policy_decisions"
    __table_args__ = (
        CheckConstraint("decision in ('ALLOW','DENY','REQUIRE_APPROVAL')", name="decision_allowed"),
        CheckConstraint("length(context_hash) = 64", name="context_hash_length"),
        Index("ix_policy_decisions_run_id", "run_id"),
        Index("ix_policy_decisions_action_id", "action_id"),
        Index("ix_policy_decisions_effect_id", "effect_proposal_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    action_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.action_proposals.id", ondelete="CASCADE"),
        nullable=False,
    )
    effect_proposal_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.effect_proposals.id", ondelete="CASCADE"),
    )
    decision: Mapped[str] = mapped_column(Text, nullable=False)
    rule_id: Mapped[str] = mapped_column(Text, nullable=False)
    context_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ApprovalRequestRow(Base):
    __tablename__ = "approval_requests"
    __table_args__ = (
        CheckConstraint(
            "status in ('PENDING','APPROVED','REJECTED','EXPIRED','CANCELLED')",
            name="status_allowed",
        ),
        CheckConstraint("expires_at > requested_at", name="expiry_after_request"),
        CheckConstraint("length(approved_context_hash) = 64", name="context_hash_length"),
        Index("ix_approval_requests_run_status", "run_id", "status"),
        Index("ix_approval_requests_effect_id", "effect_proposal_id"),
        Index(
            "ix_approval_requests_pending_expiry",
            "expires_at",
            postgresql_where=text("status = 'PENDING'"),
        ),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    effect_proposal_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.effect_proposals.id", ondelete="CASCADE"),
        nullable=False,
    )
    approved_context_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="PENDING")
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    decided_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    decision_source: Mapped[str | None] = mapped_column(Text)


class ApprovalGrantRow(Base):
    __tablename__ = "approval_grants"
    __table_args__ = (
        CheckConstraint(
            "status in ('ACTIVE','CONSUMED','EXPIRED','REVOKED')", name="status_allowed"
        ),
        CheckConstraint("expires_at > issued_at", name="expiry_after_issue"),
        CheckConstraint("length(context_hash) = 64", name="context_hash_length"),
        CheckConstraint("length(capability_hash) = 64", name="capability_hash_length"),
        CheckConstraint("length(signature) = 64", name="signature_length"),
        Index("ix_approval_grants_run_status", "run_id", "status"),
        Index("ix_approval_grants_effect_id", "effect_proposal_id"),
        Index(
            "ix_approval_grants_active_expiry",
            "expires_at",
            postgresql_where=text("status = 'ACTIVE'"),
        ),
        Index(
            "uq_approval_grants_request_active",
            "approval_request_id",
            unique=True,
            postgresql_where=text("status = 'ACTIVE'"),
        ),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    approval_request_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.approval_requests.id", ondelete="CASCADE"),
        nullable=False,
    )
    effect_proposal_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.effect_proposals.id", ondelete="CASCADE"),
        nullable=False,
    )
    context_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False)
    capability_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    capability_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    signature: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="ACTIVE")
    issued_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class SideEffectRow(Base):
    __tablename__ = "side_effects"
    __table_args__ = (
        CheckConstraint(
            "status in ('COMMITTED','VERIFIED','OUTCOME_UNKNOWN','FAILED')", name="status_allowed"
        ),
        CheckConstraint("length(request_hash) = 64", name="request_hash_length"),
        CheckConstraint(
            "response_hash is null or length(response_hash) = 64", name="response_hash_length"
        ),
        Index("ix_side_effects_run_created", "run_id", "created_at"),
        Index("ix_side_effects_effect_id", "effect_proposal_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    effect_proposal_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.effect_proposals.id", ondelete="CASCADE"),
        nullable=False,
    )
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    effect_type: Mapped[str] = mapped_column(Text, nullable=False)
    external_resource_id: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    request_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    response_hash: Mapped[str | None] = mapped_column(String(64))
    committed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class EvaluationBatchRow(Base):
    __tablename__ = "evaluation_batches"
    __table_args__ = (
        CheckConstraint(
            "status in ('queued','running','completed','failed','cancelled')",
            name="status_allowed",
        ),
        CheckConstraint("maximum_total_cost_usd > 0", name="cost_cap_positive"),
        CheckConstraint("intended_execution_count > 0", name="intent_count_positive"),
        CheckConstraint("length(manifest_hash) = 64", name="manifest_hash_length"),
        Index("ix_evaluation_batches_status_created", "status", "created_at"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    plan_id: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="queued")
    requested_by: Mapped[str] = mapped_column(Text, nullable=False)
    maximum_total_cost_usd: Mapped[Decimal] = mapped_column(Numeric(12, 4), nullable=False)
    intended_execution_count: Mapped[int] = mapped_column(Integer, nullable=False)
    manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    manifest: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_error: Mapped[str | None] = mapped_column(Text)


class EvalCaseRow(Base):
    __tablename__ = "eval_cases"
    __table_args__ = (
        UniqueConstraint("evaluation_id", "case_id", name="uq_eval_cases_batch_case"),
        CheckConstraint("length(manifest_hash) = 64", name="manifest_hash_length"),
        Index("ix_eval_cases_evaluation_id", "evaluation_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    evaluation_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.evaluation_batches.id", ondelete="CASCADE"),
        nullable=False,
    )
    case_id: Mapped[str] = mapped_column(Text, nullable=False)
    fault_class: Mapped[str] = mapped_column(Text, nullable=False)
    seed: Mapped[int] = mapped_column(Integer, nullable=False)
    manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    case_manifest: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class EvalExecutionRow(Base):
    __tablename__ = "eval_executions"
    __table_args__ = (
        CheckConstraint("arm in ('baseline','protected')", name="arm_allowed"),
        CheckConstraint(
            "status in ('intended','running','valid','infrastructure_invalid','failed')",
            name="status_allowed",
        ),
        CheckConstraint("attempt_kind in ('original','replacement')", name="attempt_kind_allowed"),
        CheckConstraint("model_cost_usd >= 0", name="model_cost_nonnegative"),
        UniqueConstraint(
            "evaluation_id", "eval_case_id", "arm", "attempt_kind", name="uq_eval_execution_intent"
        ),
        Index("ix_eval_executions_evaluation_id", "evaluation_id"),
        Index("ix_eval_executions_case_id", "eval_case_id"),
        Index("ix_eval_executions_run_id", "run_id"),
        Index("ix_eval_executions_original_id", "original_execution_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    evaluation_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.evaluation_batches.id", ondelete="CASCADE"),
        nullable=False,
    )
    eval_case_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.eval_cases.id", ondelete="CASCADE"),
        nullable=False,
    )
    run_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="SET NULL")
    )
    original_execution_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.eval_executions.id", ondelete="RESTRICT"),
    )
    arm: Mapped[str] = mapped_column(Text, nullable=False)
    attempt_kind: Mapped[str] = mapped_column(Text, nullable=False, server_default="original")
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="intended")
    oracle_version: Mapped[str] = mapped_column(Text, nullable=False)
    raw_predicate_results: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    invalid_reason: Mapped[str | None] = mapped_column(Text)
    model_cost_usd: Mapped[Decimal] = mapped_column(
        Numeric(12, 4), nullable=False, server_default="0"
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class MetricResultRow(Base):
    __tablename__ = "metric_results"
    __table_args__ = (
        UniqueConstraint(
            "evaluation_id", "metric_name", "report_version", name="uq_metric_result_version"
        ),
        Index("ix_metric_results_evaluation_id", "evaluation_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    evaluation_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.evaluation_batches.id", ondelete="CASCADE"),
        nullable=False,
    )
    metric_name: Mapped[str] = mapped_column(Text, nullable=False)
    metric_value: Mapped[Decimal] = mapped_column(Numeric(18, 8), nullable=False)
    confidence_low: Mapped[Decimal | None] = mapped_column(Numeric(18, 8))
    confidence_high: Mapped[Decimal | None] = mapped_column(Numeric(18, 8))
    report_version: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class MetricExecutionLinkRow(Base):
    __tablename__ = "metric_execution_links"
    __table_args__ = (
        Index("ix_metric_execution_links_metric_id", "metric_result_id"),
        Index("ix_metric_execution_links_execution_id", "execution_id"),
        {"schema": RUNTIME_SCHEMA},
    )

    metric_result_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.metric_results.id", ondelete="CASCADE"),
        primary_key=True,
    )
    execution_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.eval_executions.id", ondelete="CASCADE"),
        primary_key=True,
    )


class JobRow(Base):
    __tablename__ = "jobs"
    __table_args__ = (
        CheckConstraint(
            "status in ('pending','processing','completed','failed')", name="status_allowed"
        ),
        CheckConstraint("attempts >= 0", name="attempts_nonnegative"),
        Index("ix_jobs_run_id", "run_id"),
        Index(
            "ix_jobs_pending_priority_available",
            "priority",
            "available_at",
            postgresql_where=text("status = 'pending'"),
        ),
        {"schema": RUNTIME_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    job_type: Mapped[str] = mapped_column(Text, nullable=False)
    run_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE")
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="pending")
    priority: Mapped[int] = mapped_column(Integer, nullable=False, server_default="100")
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    available_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    worker_id: Mapped[str | None] = mapped_column(Text)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    last_error: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class ReplacementBookingRow(Base):
    """Synthetic Northstar side effect created in the grant transaction."""

    __tablename__ = "replacement_bookings"
    __table_args__ = (
        CheckConstraint(
            "status in ('confirmed','cancelled','voided','outcome_unknown')", name="status_allowed"
        ),
        CheckConstraint("total_additional_cost_minor >= 0", name="cost_nonnegative"),
        CheckConstraint("currency ~ '^[A-Z]{3}$'", name="currency_iso_shape"),
        CheckConstraint("length(approved_context_hash) = 64", name="context_hash_length"),
        CheckConstraint("length(contract_hash) = 64", name="contract_hash_length"),
        Index("ix_replacement_bookings_run_id", "run_id"),
        Index("ix_replacement_bookings_effect_id", "effect_proposal_id", unique=True),
        Index(
            "uq_replacement_bookings_original_confirmed",
            "run_id",
            "original_reservation_id",
            unique=True,
            postgresql_where=text("status = 'confirmed'"),
        ),
        {"schema": SANDBOX_SCHEMA},
    )

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    effect_proposal_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey(f"{RUNTIME_SCHEMA}.effect_proposals.id", ondelete="CASCADE"),
        nullable=False,
    )
    idempotency_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    original_reservation_id: Mapped[str] = mapped_column(Text, nullable=False)
    traveler_id: Mapped[str] = mapped_column(Text, nullable=False)
    booking_reference: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    approved_context_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    contract_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    semantic_context: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    total_additional_cost_minor: Mapped[int] = mapped_column(BigInteger, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="confirmed")
    committed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
